baseURL = 'https://rafaeltovar.info/'
languageCode = 'es-es'
title = 'Rafael Tovar'
theme = ['hugo-theme-shell']

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Jane Doe's Portfolio!"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "monokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "t0v4r"
  pcName = "laptop"
  workDir = "public"
  profile = "about.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 1 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
  Hola! Mi nombre es Rafael Tovar. 
  Trabajo como desarrollador y 
  me entusiasma la música y 
  la fotografía analógica. 
  A veces escribo una newsletter.
  
  ---

  Hi! My name is Rafael Tovar. 
  I work like developer. 
  I'm a fan of music and analog 
  photography. 
  Sometimes I write a newsletter 
  in spanish.

  <3
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "resources"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["Code", "https://github.com/rafaeltovar/"],
    ["Photography", "https://rafaeltovar.tumblr.com/"],
    ["Playlist", "https://open.spotify.com/user/fitopaldi?si=3d2c8c3b2bb248b8"],
    ["Newsletter", "http://eepurl.com/hxIvpb"],
#    ["Docker", "/content/sr_mayor.md"],
  ]
